POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "wallace",
    "email": "wallaceunfast7@gmail.com",
    "referrer": "502bcfa3-1654-45d8-a737-bc4e065b7ba0"
}


###

GET http://localhost:3333/invites/502bcfa3-1654-45d8-a737-bc4e065b7ba0


###

GET http://localhost:3333/subscribers/502bcfa3-1654-45d8-a737-bc4e065b7ba0/ranking/clicks


###
GET http://localhost:3333/subscribers/502bcfa3-1654-45d8-a737-bc4e065b7ba0/ranking/count


###
GET http://localhost:3333/subscribers/502bcfa3-1654-45d8-a737-bc4e065b7ba0/ranking/position

###
GET http://localhost:3333/ranking